<?php
/**
 * Copyright (c) 2024 Payfast (Pty) Ltd
 */

namespace Payfast\Payfast\Block\Payment;

use Magento\Checkout\Model\Session;
use Magento\Framework\Filesystem\Directory\ReadFactory;
use Magento\Framework\Module\Dir\Reader;
use Magento\Framework\View\Element\Template;
use Magento\Framework\View\Element\Template\Context;
use Magento\Sales\Model\OrderFactory;
use Payfast\Payfast\Helper\Data;
use Payfast\Payfast\Model\Payfast;

/**
 * Request class
 */
class Request extends Template
{

    /**
     * @var Payfast $_paymentMethod
     */
    protected Payfast $_paymentMethod;

    /**
     * @var OrderFactory
     */
    protected OrderFactory $_orderFactory;

    /**
     * @var Session
     */
    protected Session $_checkoutSession;

    /**
     * @var ReadFactory $readFactory
     */
    protected ReadFactory $readFactory;

    /**
     * @var Reader $reader
     */
    protected Reader $reader;

    /**
     * Constructor
     *
     * @param Context $context
     * @param OrderFactory $orderFactory
     * @param Session $checkoutSession
     * @param Data $pfHelper
     * @param ReadFactory $readFactory
     * @param Reader $reader
     * @param Payfast $paymentMethod
     * @param array $data
     */
    public function __construct(
        Context $context,
        OrderFactory $orderFactory,
        Session $checkoutSession,
        Data $pfHelper,
        ReadFactory $readFactory,
        Reader $reader,
        Payfast $paymentMethod,
        array $data = []
    ) {
        $this->_hssHelper       = $pfHelper;
        $this->_orderFactory    = $orderFactory;
        $this->_checkoutSession = $checkoutSession;
        parent::__construct($context, $data);
        $this->readFactory     = $readFactory;
        $this->reader          = $reader;
        $this->_paymentMethod  = $paymentMethod;
    }

    /**
     * Prepares the layout
     *
     * @return Request
     */
    protected function _prepareLayout(): Request
    {
        $this->setMessage('Redirecting to Payfast')
             ->setId('payfast_checkout')
             ->setName('payfast_checkout')
             ->setFormMethod('POST')
             ->setFormAction($this->_paymentMethod->getPayfastUrl())
             ->setFormData($this->_paymentMethod->getStandardCheckoutFormFields())
             ->setSubmitForm(
                 '<script type="text/javascript">document.getElementById( "payfast_checkout" ).submit();</script>'
             );

        return parent::_prepareLayout(); // TODO: Change the autogenerated stub
    }

    /**
     * Override to disable caching
     *
     * @return bool
     */
    public function isCacheable(): bool
    {
        return false;
    }
}
