<!--Copyright (c) 2008 PayFast (Pty) Ltd
You (being anyone who is not PayFast (Pty) Ltd) may download and use this plugin / code in your own website in conjunction with a registered and active PayFast account. If your PayFast account is terminated for any reason, you may not use this plugin / code or part thereof.
Except as expressly indicated in this licence, you may not use, copy, modify or distribute this plugin / code or part thereof in any way.-->
<h2><?php echo $this->escapeHtml($this->getMessage()); ?></h2>

<form name="<?php echo $this->escapeHtml($this->getName()); ?>"
      id="<?php echo $this->escapeHtml($this->getId()); ?>"
      action="<?php echo $this->escapeHtml($this->getFormAction()); ?>"
      method="post">

    <?php foreach($this->getFormData() as $item => $value ): ?>
        <input type="hidden" name="<?php echo $this->escapeHtml($item); ?>" value="<?php echo $this->escapeHtml($value); ?>" size="200">
    <?php endforeach; ?>
</form>
<?php echo $this->getSubmitForm(); ?>
