<!--Copyright (c) 2008 PayFast (Pty) Ltd
You (being anyone who is not PayFast (Pty) Ltd) may download and use this plugin / code in your own website in conjunction with a registered and active PayFast account. If your PayFast account is terminated for any reason, you may not use this plugin / code or part thereof.
Except as expressly indicated in this licence, you may not use, copy, modify or distribute this plugin / code or part thereof in any way.-->
<?php if ($instructions = $block->getMethod()->getInstructions()): ?>
    <div class="items <?php echo $block->escapeHtml($block->getMethodCode())?> instructions agreement content" id="payment_form_<?php echo
    $block->escapeHtml($block->getMethodCode()) ?>" style="display: none;">
        <?php echo nl2br($block->escapeHtml($instructions)) ?>
    </div>
<?php endif; ?>