<!--Copyright (c) 2008 PayFast (Pty) Ltd
You (being anyone who is not PayFast (Pty) Ltd) may download and use this plugin / code in your own website in conjunction with a registered and active PayFast account. If your PayFast account is terminated for any reason, you may not use this plugin / code or part thereof.
Except as expressly indicated in this licence, you may not use, copy, modify or distribute this plugin / code or part thereof in any way.-->
<div class="rk button">
    <form action="<?php echo $block->getGateUrl(); ?>" method="POST">
        <?php foreach($block->getPostData() as $key=>$value): ?>
            <input type="hidden" name="<?php echo $key; ?>" value="<?php echo $value; ?>"></input>
        <?php endforeach; ?>
        <button type="submit">Pay</button>
    </form>


</div>